#!/usr/bin/env python3
import sys
import runpy

if __name__ == "__main__":
    if len(sys.argv) > 1:
        first_arg = sys.argv[1]
        if first_arg == "--shortcut":
            if len(sys.argv) > 2:
                sys.argv = [sys.argv[0], sys.argv[2]]
            else:
                sys.argv = [sys.argv[0]]
            runpy.run_module("faugus.shortcut", run_name="__main__")
        elif first_arg == "--game":
            if len(sys.argv) > 2:
                sys.argv = [sys.argv[0], "--game", sys.argv[2]]
            else:
                sys.argv = [sys.argv[0], "--game"]
            runpy.run_module("faugus.runner", run_name="__main__")
        elif first_arg == "--run":
            if len(sys.argv) > 2:
                sys.argv = [sys.argv[0], sys.argv[2]]
            else:
                sys.argv = [sys.argv[0]]
            runpy.run_module("faugus.runner", run_name="__main__")
        else:
            runpy.run_module("faugus.launcher", run_name="__main__")
    else:
        runpy.run_module("faugus.launcher", run_name="__main__")
